name: Publish-to-npm

on:
  pull_request:
    branches: [main]
    types: 
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create a build
        run: npm link

      - name: Loggin in to NPM
        run: npm adduser
        env: 
          NPM_EMAIL: ${{ vars.EMAIL }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publishing the package
        run: npm publish